/**
 * Telling the listener that the voice they are hearing is not a person
 * speaking their language.
 *
 * WHY THIS EXISTS, AND WHY IT IS NOT A SETTING. Real-time translation removes
 * the barrier that limits who a fraudster can target: it lets somebody run a
 * romance or payment scam in a language they do not speak a word of. That is
 * this product working exactly as designed, which is precisely why the abuse
 * case cannot be engineered away.
 *
 * What CAN be removed is the deception. The con depends on the victim believing
 * a person is speaking to them. A listener who has been told plainly that the
 * voice is machine-generated has largely been inoculated, and no identity check
 * on the speaker achieves that — a verified account defrauds just as well, and
 * organised fraudsters buy documents.
 *
 * So: undismissable, not a preference, and rendered in the LISTENER'S OWN
 * LANGUAGE. A warning in a language the person does not read is decoration.
 *
 * SHOWN ONLY WHEN TRANSLATION IS ACTUALLY IN PLAY. A notice that appears on
 * every call, including ones where everybody shares a language and nothing is
 * translated, is a notice people learn to ignore — and then it is not there
 * when it matters. Crying wolf is the failure mode, so the caller gates this on
 * translation genuinely being expected for this listener.
 */

/** The languages the call application offers. Kept in step with CALL_LANGUAGES. */
export type DisclosureLanguage = 'en' | 'fr' | 'es';

export interface TranslationDisclosure {
  /** Persistent on-screen text. Short, because it must survive a small screen. */
  readonly banner: string;
  /**
   * Said aloud once, when the call begins.
   *
   * Fuller than the banner: somebody who is being deceived may not be looking
   * at the screen, and on a phone held to the ear they certainly are not. The
   * spoken form is the one that reaches them.
   */
  readonly spoken: string;
  /**
   * BCP-47 tag, for the `lang` attribute and for speech synthesis voice
   * selection. Without it a browser reads French text with an English voice
   * and the result is not comprehensible to the person it was written for.
   */
  readonly locale: string;
}

/*
 * Authored per language rather than machine-translated at runtime.
 *
 * Translating the anti-deception warning with the same engine whose output it
 * is warning about would be circular: if the engine is wrong, the warning is
 * wrong too, and it fails silently in exactly the case it exists for.
 */
const DISCLOSURES: Readonly<Record<DisclosureLanguage, TranslationDisclosure>> = {
  en: {
    banner: 'Automated translation — the other person is not speaking English.',
    spoken:
      'Automated translation. The other person is not speaking English. The voice you hear is generated by a computer.',
    locale: 'en',
  },
  fr: {
    banner: "Traduction automatique — votre interlocuteur ne parle pas français.",
    spoken:
      "Traduction automatique. Votre interlocuteur ne parle pas français. La voix que vous entendez est générée par un ordinateur.",
    locale: 'fr',
  },
  es: {
    banner: 'Traducción automática — la otra persona no está hablando español.',
    spoken:
      'Traducción automática. La otra persona no está hablando español. La voz que escucha es generada por un ordenador.',
    locale: 'es',
  },
};

/**
 * The disclosure for a listener's language.
 *
 * Falls back to English rather than to nothing. An unrecognised language means
 * somebody added one and did not write the warning; showing a warning the
 * listener may not read is bad, and showing none at all is worse.
 */
export function translationDisclosureFor(language: string): TranslationDisclosure {
  const known = DISCLOSURES[language as DisclosureLanguage];
  return known ?? DISCLOSURES.en;
}

/** Every language for which a disclosure has actually been written. */
export function disclosedLanguages(): readonly DisclosureLanguage[] {
  return Object.keys(DISCLOSURES) as DisclosureLanguage[];
}

type UtteranceFactory = (text: string) => { lang: string; rate: number };

function browserSynthesis(): SpeechSynthesis | undefined {
  return typeof globalThis === 'undefined'
    ? undefined
    : (globalThis as { speechSynthesis?: SpeechSynthesis }).speechSynthesis;
}

/*
 * Resolved separately from the synthesiser, because they are two globals and
 * only one of them was being checked. A runtime with `speechSynthesis` but no
 * `SpeechSynthesisUtterance` constructor would have thrown into the catch and
 * looked identical to "this browser cannot speak" -- a silent failure in an
 * anti-deception control is exactly the kind that is never noticed.
 */
function browserUtteranceFactory(): UtteranceFactory | undefined {
  const ctor = (
    globalThis as unknown as {
      SpeechSynthesisUtterance?: new (text: string) => { lang: string; rate: number };
    }
  ).SpeechSynthesisUtterance;
  if (typeof ctor !== 'function') return undefined;
  return (text: string) => new ctor(text);
}

/**
 * Say the disclosure aloud, once.
 *
 * BEST EFFORT, DELIBERATELY. Speech synthesis is unavailable in some browsers,
 * blocked before a user gesture in others, and has no voice for some locales.
 * None of those may break the call, and none of them may suppress the visible
 * banner — the banner is the guarantee and this is the reinforcement.
 *
 * Returns whether speech was actually dispatched, so a caller can tell the
 * difference between "spoken" and "silently unavailable" rather than assuming.
 */
export function speakDisclosure(
  disclosure: TranslationDisclosure,
  synthesis: SpeechSynthesis | undefined = browserSynthesis(),
  createUtterance: UtteranceFactory | undefined = browserUtteranceFactory(),
): boolean {
  if (!synthesis || typeof synthesis.speak !== 'function') return false;
  if (!createUtterance) return false;
  try {
    const utterance = createUtterance(disclosure.spoken);
    utterance.lang = disclosure.locale;
    // Slightly under normal pace: this is a warning somebody is hearing for
    // the first time, in a language the other party is not speaking.
    utterance.rate = 0.95;
    synthesis.speak(utterance as unknown as SpeechSynthesisUtterance);
    return true;
  } catch {
    // A failed announcement must never take a call down.
    return false;
  }
}
